# Generated by Django 5.2.8 on 2026-03-11 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_recommandations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('HOTEL', 'Hébergement / Hôtel'), ('RESTO', 'Restauration / Snack'), ('GUIDE', 'Guide Touristique'), ('TRANSPORT', 'Transport / Location'), ('LOISIR', 'Loisir / Activité')], max_length=20)),
                ('prix_total', models.DecimalField(decimal_places=2, help_text='Prix total du service en FCFA', max_digits=10)),
                ('montant_acompte', models.DecimalField(decimal_places=2, help_text="Montant de l'acompte (ticket d'entrée)", max_digits=10)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='services/images/')),
                ('est_valide', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('prestataire', models.ForeignKey(limit_choices_to={'role': 'pro'}, on_delete=django.db.models.deletion.CASCADE, related_name='services_proposes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente de paiement'), ('CONFIRME', 'Confirmée (Acompte payé)'), ('ANNULE', 'Annulée'), ('TERMINE', 'Service rendu')], default='ATTENTE', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acompte_paye', models.BooleanField(default=False)),
                ('code_ticket', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('touriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_reservations', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_recues', to='core.service')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=255)),
                ('date_evenement', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
                ('services_associes', models.ManyToManyField(blank=True, related_name='evenements', to='core.service')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(help_text='Note de 1 à 5')),
                ('commentaire', models.TextField()),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_avis', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_clients', to='core.service')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('FERME', 'Fermé')], default='OUVERT', max_length=20)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('agent_support', models.ForeignKey(blank=True, limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Support',
                'verbose_name_plural': 'Tickets Support',
            },
        ),
    ]
